FROM node:carbon

ENV HEROKU=true

WORKDIR /code

RUN npm install npm@latest -g && npm -v
RUN npm install -g serve
COPY . .
RUN cd blockchain/ && npm ci && cd -

ARG PORT=$PORT
RUN echo $PORT

CMD serve -l $PORT
