// Generated by CoffeeScript 2.4.1
var _, app, express, log, to_fix;

express = require('express');

app = express();

app.use(express.static('./'));

app.use(express.json());

app.use(function(req, res, next) {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  return next();
});

app.use(function(req, res, next) {
  res.status(404);
  res.send('Not found');
});

app.use(function(err, req, res, next) {
  log((new Date).getTime(), err);
  res.status(err.status || 500);
  res.send('Internal error');
});

app.listen(8080, function() {

});

//# sourceMappingURL=server.js.map
